buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'io.github.opendcs.maven:maven-central-upload:0.1.1'
    }
}
plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'com.palantir.git-version' version '3.2.0'
    id 'io.github.opendcs.maven.maven-central-upload' version '0.1.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
    withJavadocJar()
    withSourcesJar()
}

group = "io.github.opendcs"
archivesBaseName = "java-algebra-system"

def static versionLabel(gitInfo) {
    def branch = gitInfo.branchName // all branches are snapshots, only tags get released
    def tag = gitInfo.lastTag
    // tag is returned as is. Branch may need cleanup
    return branch == null ? tag : 99 + "." + branch.replace("/", "-") + "-SNAPSHOT"
}

def tmp_version = project.findProperty("versionOverride") ?: versionLabel(versionDetails())
version = tmp_version

repositories {
    mavenCentral()
}

tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none','-quiet')
    failOnError false
}

dependencies {
    implementation 'org.processing:core:3.3.7'

    testImplementation 'org.mockito:mockito-core:3.4.6'
    testImplementation 'org.mockito:mockito-junit-jupiter:3.4.6'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.6.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.9.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.9.0'
}

test {
    useJUnitPlatform()
}


publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'java-algebra-system'
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'Java Algebra System'
                description = 'Library for computer algebra work.'
                url = 'https://github.com/opendcs/java-algebra-system'
                scm {
                    connection = 'scm:git:https://github.com/opendcs/java-algebra-system'
                    developerConnection = 'scm:git:git@github.com:opendcs/java-algebra-system.git'
                    url = 'https://github.com/opendcs/java-algebra-system'
                }

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/license/mit/'
                    }
                }

                developers {
                    developer {
                        id = 'jiachenren'
                        name = 'Jiachen Ren'
                        email = 'https://github.com/JiachenRen'
                    }
                    developer {
                        id = 'opendcs-team'
                        name = 'OpenDCS Dev Team'
                        email = 'https://github.com/opendcs' 
                    }
                }
            }
        }
    }

    repositories {
        maven {
            name = "mavenCentralApi"
            url = "https://central.sonatype.com"
            def user = project.findProperty("centralApiUsername")
            def passwd = project.findProperty("centralApiPassword")
            credentials {
                username = user
                password = passwd
            }
        }
    }
}

signing {
    def signingKey = (project.findProperty("signingKey")?: "").trim().replace("\n","")
    def signingPassword = project.findProperty("signingKeyPassword")?: ""
    useInMemoryPgpKeys(signingKey, signingPassword)
    sign publishing.publications.withType(MavenPublication)
}
